-- AlterTable
ALTER TABLE "Folder" ADD COLUMN "color" TEXT DEFAULT '#3B82F6',
ADD COLUMN "icon" TEXT DEFAULT 'folder',
ADD COLUMN "isDefault" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "pin" TEXT,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
